<?php

use Livewire\Volt\Component;
use function Livewire\Volt\{state, mount, rules};
use Illuminate\Support\Collection;

new class extends Component {

    public $messages = [];
    public $conversationId;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($conversationId = null)
    {
        $this->conversationId = $conversationId ?? \Illuminate\Support\Str::uuid();

        $this->messages = collect([]);

        // 2. Load existing or default messages
        if (is_null($this->messages)) {
            // We initialize messages as a Collection for easy handling and pre-load a welcome message
            $this->messages = Collection::make([
                ['role' => 'bot', 'text' => 'Hello! I am your AI assistant. How can I help you today?'],
            ]);
        }
    }


};


// State for user input and the message history
state(['prompt' => '', 'messages' => [], 'conversationId' => null]);

// Rules for input validation
rules(['prompt' => ['required', 'string', 'max:2000']]);

// --- Actions ---

// The core action to send the message and get the AI response
$send = function () {
    // 1. Validate the user input
    $this->validate([
        'prompt'    => 'required|string'
    ]);

    $userPrompt = $this->prompt;

    // 2. Add the user's message to the state
    $this->messages[] = ['role' => 'user', 'text' => $userPrompt];
    $this->prompt = ''; // Clear input immediately

    // 3. Trigger component refresh/scroll before the AI response (optional, for UX)
    $this->skipRender();
    $this->js('document.getElementById("chatContainer").scrollTop = document.getElementById("chatContainer").scrollHeight');

    // 4. Call the Chat Controller (The actual implementation goes here)
    // NOTE: Replace the $this->getAiResponse() call with your actual controller logic.
    $controller = app(\App\Http\Controllers\ChatController::class);

    // 5. Add the AI response to the state
//    $this->messages[] = ['role' => 'bot', 'text' => $aiResponseText];

    // 6. Force a final scroll after receiving the response
    $this->js('document.getElementById("chatContainer").scrollTop = document.getElementById("chatContainer").scrollHeight');
};


// Helper function to simulate the AI response (Replace this with your ChatController call)
$simulateAiResponse = function (string $prompt): string {
    // --- THIS IS WHERE YOU INTEGRATE YOUR CHAT CONTROLLER ---

    // Example logic to demonstrate a dynamic response:
    if (stripos($prompt, 'volt') !== false) {
        return "Laravel Volt is a functional API for Livewire that supports single-file components. It helps reduce boilerplate and keeps PHP logic and Blade templates colocated.";
    } elseif (stripos($prompt, 'strategy') !== false) {
        return "The Strategy Design Pattern is excellent for handling interchangeable AI services (like Gemini, OpenAI, etc.) in your ChatController! You can switch implementations easily.";
    }

    return "Thank you for asking! I've processed your request: \"{$prompt}\". A full answer would be generated by your integrated ChatController now.";
};

?>

<div class=" dark:text-white text-neutral-500 flex items-center justify-center px-6"
     id="chat-interface-{{ $conversationId ?? 'default' }}">

    <div class="w-full max-w-2xl">

        <h1 class="text-3xl md:text-4xl font-extrabold tracking-tight text-center">How can I help you today?</h1>


        <div id="chatContainer-{{ $conversationId ?? 'default' }}"
             class="mt-8 {{ isset($messages) && count($messages) > 0 ? '' : 'hidden' }}">

            <div id="messages-{{ $conversationId ?? 'default' }}" class="space-y-4"></div>

            <div id="typingIndicator-{{ $conversationId ?? 'default' }}" class="hidden"></div>

        </div>


        <div class="mt-6">

            {{--            <form id="chatForm-{{ $conversationId ?? 'default' }}" onsubmit="return sendMessage(event, '{{ $conversationId ?? 'default' }}')">--}}
            <form id="chatForm-{{ $conversationId ?? 'default' }}" wire:submit.prevent="send">

                @csrf

                <div class="relative">

                    <div
                        class="flex items-center bg-neutral-100 dark:bg-neutral-800 border border-neutral-100 dark:border-neutral-700 rounded-xl shadow-sm">

                        <input

                            type="text"
                            wire:model="prompt"

                            id="messageInput-{{ $conversationId ?? 'default' }}"

                            placeholder="write something.."

                            class="flex-1 bg-transparent border-none focus:outline-none w-full text-gray-700 dark:text-white placeholder:text-neutral-400 px-4 py-3"

                            autocomplete="off"

                        >

                        <button

                            type="submit"

                            id="sendButton-{{ $conversationId ?? 'default' }}"

                            class="m-2 px-5 h-9 rounded-md bg-neutral-200 hover:bg-neutral-300 hover:cursor-pointer dark:bg-neutral-900 text-neutral-900 dark:text-neutral-500 flex items-center justify-center transition-colors"

                        >

                            <i class="fas fa-arrow-up"></i>

                            send

                        </button>

                    </div>

                </div>

            </form>

        </div>

    </div>

</div>

<script>
    // Simple JavaScript to ensure the chat scrolls to the bottom on load
    window.onload = function () {
        const chatContainer = document.getElementById('chatContainer');
        if (chatContainer) {
            chatContainer.scrollTop = chatContainer.scrollHeight;
        }
    };
</script>
